### ISSUE TITLE
Disable merging without review + passing tests

### ISSUE THREAD

**Issue by thedrow** [hpyproject/hpy#104]
Right now, anyone with write privileges can merge a PR even if it isn't ready.
We should block that to avoid any mistakes.

I wanted to label a PR and almost merged it by accident.

**Comment by hodgestar** [comment]
My 2c is that I'd prefer not to rigidly enforce rules around merging right now. I agree that reviews and passing tests are a good idea (especially the latter) but I don't want to have contributors forced to wait to merge. If there is a way to help avoid mistakes but still allow contributors to override and merge anyway, I'm all for that.

**Comment by thedrow** [comment]
Overriding a merge can be done if you have admin access.

Waiting for a merge isn't necessary if we have a bot that merges PRs which are considered approved.

**Comment by antocuni** [comment]
I am -0.5 on the idea. Although it would be nice in principle, it probably introduce some unnecessary friction in practice.
E.g., it happens to sometimes to open a PR just to merge it immediately, because it's a small feature, I am confident it is right and I need it to go further in the development (see e.g. #91).

Currently, we don't seem to have a problem with people merging PRs when they shouldn't, so I think this fixes a non-issue. But I am open to reconsider it if it becomes a real problem.

**Comment by hodgestar** [comment]
Closing this for now because it seems not to be a problem in practice, but happy to revisit the issue later if needed.
