### ISSUE TITLE
Documentation of the ctx object

### ISSUE THREAD

**Issue by prescod** [hpyproject/hpy#149]
API.md says:

> The ctx is an opaque "context" argument that stands for the current interpreter.

But it seems this is not true because some extension code uses substructure in the ctx object.

**Comment by fangerer** [comment]
Sorry that no one ever responded to this issue. I'm currently working on milestone `ABI version 1` and we will also improve documentation for this.
Anyway, concerning your comment: 

> But it seems this is not true because some extension code uses substructure in the ctx object.

That's true. The HPy context isn't opaque since extension authors are also asked to use handles like `ctx->h_None`.
I need to admit that I didn't realize existence of file `docs/api.md` since there is `docs/api.rst` (which is used in the official [documentation](https://docs.hpyproject.org/en/latest/api.html)). It looks like `docs/api.md` is just an out-dated artifact from the very early HPy days which collected some ideas. Thanks for pointing that out. I'll remove that file and will move the valid parts to other locations.
