### ISSUE TITLE
Rename HPyContext to HPyContext*

### ISSUE THREAD

**Issue by antocuni** [hpyproject/hpy#150]
This is related to #149 but I prefer to open a new issue because it's something API design instead of "just" a documentation issue.

The original idea of `HPyContext` was to be fully opaque and as such we decided to call the type because it was not important for the user to know it is a pointer (a bit like Windows' `HANDLE`). But later we started to add `ctx->h_None` & co., meaning that the user is expected to know it's a pointer.

So, for clarity I propose to rename all `HPyContext` to `HPyContext *` (and tweak the typedef appropriately of course). This obviously breaks all the existing code, but fortunately we don't have that much around, and a simply find&replace should cover 99.9% of the cases anyway.

**Comment by hodgestar** [comment]
Renaming to `HPyContext *` makes sense to me. My reasoning:

* The layout of the context can't be truly opaque because compiled universal modules have to be able to do ctx->method even if these dereferences are usually hidden inside methods supplied by HPy itself.

* I can't think of a good way to make the API level opaque -- e.g. `HPy_h_None(ctx)` to get `h_None` looks quite horrible, whereas `ctx->h_None` doesn't look too bad and at least makes it clear that this is just a pointer to a fixed handle.

One downside to the current situation is that it's very tempting to write just `ctx->h_None` instead of `HPy_Dup(ctx->h_None)` so perhaps there is a case to me made to have methods like `HPy_Dup_None(ctx)` instead.

**Comment by antocuni** [comment]
> One downside to the current situation is that it's very tempting to write just `ctx->h_None` instead of `HPy_Dup(ctx->h_None)` so perhaps there is a case to me made to have methods like `HPy_Dup_None(ctx)` instead.

Note that dup is not always what you want. If you want to pass `None` to a function, you just write `h_None`, the dup is needed only to return it. So, since we have to keep `h_None`, having `HPy_Dup_None` doesn't look any better than `HPy_Dup(ctx->None)`.

**Comment by hodgestar** [comment]
Implemented in #182.
