### ISSUE TITLE
Port creation and destruction of ndarray objects to HPy

### ISSUE THREAD

**Issue by rlamy** [hpyproject/hpy#252]
The next step for #137 is to handle the lifecycle of ndarray objects in HPy. Concretely, this means:
* Convert the following legacy slots to their HPy equivalents: Py_tp_dealloc, Py_tp_alloc, Py_tp_new, Py_tp_free
* Replace all `PyObject*` members in the `PyArrayObject` struct with `HPyField`
* Ensure that all the object references held by the ndarray can be traced by the GC

**Comment by rlamy** [comment]
Thanks for the link, that will be useful. The `HPyField` mechanism does indeed require implementing cyclic GC support on CPython. However, the API is different since HPy attempts to abstract over the differences between CPython and non-refcounted implementations, so the C code can't be reused directly. OTOH, passing the tests from that PR is clearly a goal.

**Comment by rlamy** [comment]
@thedrow Sorry for the late answer, I had to attend to urgent family matters this week. As I've started working on this, I expected to finish it on my own, and I don't think it can be split easily.

**Comment by rlamy** [comment]
Dealing with arrays that contain objects, and particularly [structured arrays](https://numpy.org/doc/stable/user/basics.rec.html), raises some issues with HPyFields:

* To handle unaligned data, code like this needs to work:
```C
void setitem(HPyContext *ctx, char *data, HPy item) {
    HPyField f;
    memcpy(&f, data, sizeof(f));
    HPyField_Store(ctx, owner, &f, item);
    memcpy(data, &f, sizeof(f));
    return;
}
```
* Reading or writing to a field requires knowing the owning array. Many internal numpy functions pass around only the data pointer, which makes them hard to port - it's sometimes even unclear who the owner is.
* In some cases, upstream numpy copies a block of memory containing PyObjects and, later on, updates the refcounts by walking the copy. Emulating that with HPy requires code like:
```C
void fix_field_owner(HPyContext *ctx, HPy src_array, HPy dst_array, HPyField *f) {
    HPy item = HPy_Load(ctx, src_array, *f);
    *f = HPyField_NULL;  // break identification between source field and its copy 
    HPyField_Store(ctx, dst_array, f, item); // INCREFs item on CPython
    HPy_Close(ctx, item);
    return;
}
```
* The information required to traverse fields in the array's data is currently only accessible through the dtype, which is a field of the array. However, tp_traverse doesn't receive a context and isn't supposed to call the HPy API. Can we somehow read the dtype from tp_traverse or do we have to precompute the location of all fields?

**Comment by hodgestar** [comment]
For the memcpy issue, perhaps we could write an `HPyField_Copy` that does the memcpy and then ensures the GC can be happy by doing whatever is needed.

**Comment by seberg** [comment]
@rlamy if it helps to have a NumPy side view, maybe join one of our triage meetings?  Usually wednesdays bi-weekly (not this week) https://hackmd.io/68i_JvOYQfy9ERiHgXMPvg
I can't quite make sense of all of the impact here.  The `owner` stuff worries me slightly, because I am not sure our `arr->base` is quite up for the task (at least not easily), so I am curious to see how a solution may look like.
It seems the `owner` may be mainly about locking and may not have to be an exact "owner" (i.e. the object owning the storage area)?

**Comment by steve-s** [comment]
> It seems the owner may be mainly about locking and may not have to be an exact "owner" (i.e. the object owning the storage area)?

Yes that sounds like one legitimate use-case. I think the use-case this was primarily designed for are write/read barriers in generational and other GCs that need them. If you have old/young generation, you need to track what young objects are pointed by old objects so that you do not have to scan the old generation when doing young generation only GC. The write barrier keeps track of that. The implementation usually takes advantage of some knowledge of the memory layout and masks some bits from the "owner" and the "value" to quickly find out if they are from old/young generations. If it did not get the *handle* of the "owner", it may need more indirection&book keeping and would be more costly.

**Comment by steve-s** [comment]
@hodgestar
> For the memcpy issue, perhaps we could write an HPyField_Copy that does the memcpy and then ensures the GC can be happy by doing whatever is needed.

This will not work if the memory that you are copying is, for example, an array of structs like this:
```
struct {
  int field1;
  void* field2;
  HPyField field3;
};
```
the `HPyField_Copy` wouldn't know, which parts of the memory are HPyFields and which just some unrelated raw data.

**Comment by steve-s** [comment]
So going over the points @rlamy posted above in https://github.com/hpyproject/hpy/issues/252#issuecomment-1013224066

* `setitem`: so this does not work currently? How is `HPyField` struct, in this respect, different from other structs/types that numpy puts at unaligned addresses?
* required knowing the owning array: I think this is very important feature. For example, GraalPython cannot put actual references to the objects into the raw memory, because Java GC has no idea about it and does not scan it at all. GraalPython puts only handles in there and then keeps lookup map for them (the map itself is a proper GC managed Java object associated with the owner). When the owning object dies, all objects referenced from the lookup map, i.e., from the HPyFields, are not reachable via that object anymore. I suspect that any Python implementation based on existing runtime like JVM/.NET/... will have this issue. Moreover, I suspect that other implementations that have full control of the GC, like Pypy, will still need that for generational barriers? Maybe in that case one can just assume the worst case (i.e., mark the item as being referenced from old gen regardless of whether the owner was really from old gen)? In GraalPython case I don't see any way without knowing the owner -- we need to tell our GC about the relationship by establishing it in the GC managed memory. We cannot teach the GC that it should call `tp_traverse` when scanning the heap.
* this point looks like an annoyance, but it is not a fundamental issue? Maybe HPy can offer `HPyField_FixCopy(ctx, old_owner, old_field, new_owner, new_field)`? We should maybe specify that it must be called immediately after the copy was made there must not be any HPy API (or CPython API) calls between the copying and calling `HPyField_FixCopy`?
* I would say that, unfortunately, pre-computing is the only way. Could you something like this:
```
struct {
  size_t *obj_offsets; // offsets within one array item that contain objects
  size_t *nested_offsets; // offsets within one array item that contain nested data
  size_t obj_offsets_size, nested_offsets_size;
  size_t item_size;
} data_item_info;
```
have this structure be always at `data - sizeof(data_info)`, i.e., put before the data and also before any nested data. The offsets would be within one item, so with this one could scan the array per item, within each item identify HPyFields and also recursive data to visit (which would also have their `data_item_info`). Couldn't this be a general improvement for numpy regardless of the HPy port, because it can speed up traversing the data when fixing up refcounts?

**Comment by hodgestar** [comment]
> > For the memcpy issue, perhaps we could write an HPyField_Copy that does the memcpy and then ensures the GC can be happy by doing whatever is needed.
> 
> This will not work if the memory that you are copying is, for example, an array of structs like this:

My idea was slightly more advanced than this -- by "ensures the GC can be happy by doing whatever is needed" I mean an HPyField_Copy that does something like copy memory from `(orig_owner, orig_pointer, len)` to `(copy_owner, copy_pointer)` and then calls `tp_traverse` on the new owner before returning.

**Comment by hodgestar** [comment]
@steve-s Maybe my `HPyField_Copy` is the copy plus your `HPyField_FixCopy` in one. The `FixCopy` seems like a bad idea to -- something will be left in broken state between the copy and the call to `FixCopy` and why have that if we can avoid it?

**Comment by steve-s** [comment]
> My idea was slightly more advanced than this -- by "ensures the GC can be happy by doing whatever is needed" I mean an HPyField_Copy that does something like copy memory from (orig_owner, orig_pointer, len) to (copy_owner, copy_pointer) and then calls tp_traverse on the new owner before returning.

It seems to me that this could be lot of unnecessary work? `tp_traverse` would traverse everything, possibly other parts of the memory that were not touched by the copy.

**Comment by seberg** [comment]
Sorry to barge in, but I need to redo getitem/setitem.  Basically, as far as I understand it now, both `getitem` and `setitem` *must* be passed an `owner` object.  This `owner` can be identical to the "memory owner", I think (if you own the references, you should own the memory they are stored in) – NumPy has a concept for `owner`, it is just a bit harder to get than I would like (it is actually worse than that, because we have no way to know that `arr.base` points to the *real* owner, or just an object that keeps the real owner alive.  We may need to store the owner more explicitly or add checks/assumptions around `arr.base`...).

In practice, the `owner` passed into these functions would be allowed to be NULL if an array contains no references.  `owner` is also a fully opaque Python object.

In some cases, buffers may be ephemeral (i.e. local to some function scope), in which case we still need an `owner`, though.  I expect this is easy: We just need some objects that can be the "owner" there.  (It may need a free-list/stack of objects to use and put back, but no problem there.)

The other problem is that all *functions*, including casts (and traverse hopefully) need the `owner` as well (so long they work with references).  This is not a big problem either, it just means we have to fill in the `owner` and pass it through as part of the `ArrayMethod`s context (sorry newer internal NumPy API here) – it is a bit annoying that we need to traverse `arr.base` to find the actual `owner`, but for now: whatever.

I was briefly considering whether the dtype can be the owner.  I do not think that makes sense, the object that owns the buffer where the references are stored is the natural owner (the array normally).  Although, there *could* be dtypes where the dtype *is* the owner :), but this is even less of a problem.

**Comment by leonmck-dsp-dev** [comment]
id love to collaborate to solve this

**Comment by steve-s** [comment]
I think we can say that the `owner` from the point of view of HPy should be whichever object will `VISIT` given `HPyField` in its `tp_traverse`. We also need to ensure that there is only one, i.e., not more than one object will `VISIT` the same field in `tp_traverse`. Does this match the current notion of the owner?

Can there be some sharing of the raw array data between different array objects? That would be also important situation to consider.

**Comment by seberg** [comment]
> Can there be some sharing of the raw array data between different array objects? That would be also important situation to consider.

Yes, the (probably not big) issue is that we do not keep track super well of the `owner` in the sense of "the object implementing `VISIT` for the content" (right now we only have to care that it holds a – possibly indirect – reference to it).

But I don't think it matters, as you said, the `owner` is the object that does the `VISIT` (a nice clear definition).  If two arrays share their memory, one just has `arr.owner = other_array` and its traverse will onl do `VISIT(other_arr)`.  `other_arr` as the true owner, visits its elements.

What, I guess, matters is that:
1. We need to pass around `owner` in many places were we do not (getitem, setitem and generally basically everywhere).  In some cases we currently pass around the array itself, those seem OK(ish).
   * I would prefer not pass around the array, it is bad API, e.g. tricky to use with buffers because it makes promises that we can't keep.  It would be better if `owner` is an opaque pointer.
   * `arr.base` should eventually point to the "owner", but we have no strict guarantees, currently.  This is likely OK in practice, as it may just limits some weirder stuff...  But we may want to consider introducing `arr.owner` to simplify things.
2. We have buffers (sometimes static ones).  I am not sure this is too bad:
    * Many buffer are "largish", we could really just wrap them into objects (in some cases we _should_ do that anyway probably).
    * There are some static buffers or buffers where creating an owning object is less obvious.  So I think we may need to say that `owner` must be considered ephemeral by API functions.  You are not allowed to hold on to it.  That way, those buffers can just reuse the input array as the "owner".  (To be clear, the `owner` in this sense does not necessary keep the buffer alive, it just owns the references _inside_ the buffer.)  This may mean that in rare cases we should pass `owner` *and* `base` (which usually will be identical)

**Comment by rlamy** [comment]
@steve-s 
`setitem` does appear to work. However, it contradicts the [porting guide](https://docs.hpyproject.org/en/latest/porting-guide.html) and indeed there is an issue if the GC kicks in between HPyStore() and the memcpy() back to the owner - because `tp_traverse` still points to the old version of the contents. Now, I think it's OK for GraalPython, because it doesn't use `tp_traverse`, and for PyPy, because the GC can't run in the middle of a C function, but on CPython, HPyField_Store can trigger execution of arbitrary code. Note that our CPython implementations of HPyField_Store have the same issue internally, because they decref the old value before updating the field. And so does upstream numpy `OBJECT_setitem`, AFAICT.

**Comment by steve-s** [comment]
@rlamy
Ah, yes now I see the problem with `setitem`. Would it make sense to introduce `HPyField_StoreUnaligned(HPyContext *ctx, HPy owner, char *buffer, HPy_size_t offset, HPy value)` and also `HPyField_LoadUnaligned` for this? Re current implementation of `HPyField_Store`: shouldn't it then first store the object into local variable, then override the field and only then decref the object, i.e., kind of what `Py_CLEAR` does. In code:

```
ctx_Field_Store(HPyContext *ctx, HPy target_object, HPyField *target_field, HPy h)
{
    PyObject *obj = _h2py(h);
    PyObject *target_obj = _hf2py(*target_field);
    Py_XINCREF(obj);
    *target_field = _py2hf(obj);
    Py_XDECREF(target_obj);
```

I can make a PR if this looks good. CC @antocuni 


>  Oooops? Above I somewhat assumed that it is OK for an ephemeral buffer to have an owner who does not know how to visit. Is that actually true!? It seems like it may not be?

Yes, AFAICS, there must always be someone who VISITs the HPyFields, otherwise the objects they point to may be assumed garbage and collected. Maybe something important that I should have added to the "definition" of the owner (object that VISITs). HPy uses the `tp_traverse` in HPy's implementation of `tp_dealloc` to find out which objects to decref (HPy does not allow user provided implementations of `tp_dealloc`).

**Comment by rlamy** [comment]
@steve-s I think that HPyField_StoreUnaligned/HPyField_LoadUnaligned are too specialised to be part of the API. AFAICT, the issue can be fixed on the user side by holding on to a handle to the old value of the field until the last `memcpy`, i.e. the pattern becomes:
```
void setitem(HPyContext *ctx, char *data, HPy item) {
    HPyField f;
    memcpy(&f, data, sizeof(f));
    HPy keep_alive = HPyField_Load(ctx, owner, f);
    HPyField_Store(ctx, owner, &f, item);
    memcpy(data, &f, sizeof(f));
    HPy_Close(ctx, keep_alive);
    return;
}
```
Note that `item` should also be kept alive until the end of the function, as it's implementation-dependent whether `owner` holds a reference to it between the HPyField_Store and the memcpy.
+1 for the fix to `HPyField_Store` (see also the discussions around CPython's internal macro `Py_SETREF`, e.g. [here](https://bugs.python.org/issue20440))

**Comment by seberg** [comment]
One thing I forgot before: Providing a traverse that prepares things ahead of time is probably the better API to begin with.  I.e. I was considering that as an evolution to the current dealloc anyway, the current stuff can't be extended to user DTypes well and also it has light use of Python API that could fail in theory.
So that needs API extension and some figuring out, but I think the approximate path is clear. 

Providing owners and especially traverse for temporary buffers is what still worries me slightly, as in: I don't know how the pattern to fix this would look like and I am not even sure all the ways we use such buffers.

**Comment by rlamy** [comment]
We decided to give up on supporting object dtypes for now, and to limit the conversion to what's covered by the Array API. So I've rolled back, and rebased over a recent main, the [hpy branch](https://github.com/hpyproject/numpy-hpy/tree/hpy) to a state where only ndarray attributes have been converted to HPyField, but not the contents of `PyArray_DATA(array)`. The partial implementation of the latter was moved to the [hpy-convert-object-dtype branch](https://github.com/hpyproject/numpy-hpy/tree/hpy-convert-object-dtype).

**Comment by seberg** [comment]
Sounds fair.  I would love some clarity on `owner`.  Would it help to just include it into `getitem` and `setitem` for example?  Even if we only pass `NULL` for now and say that it will be used in HPy at some point?
Or is it better to just ignore the problem for now, meaning that we may need to transition to a newer API at some point?  (I guess in practice it could be transitioning only those who deal with references.)

**Comment by rlamy** [comment]
@seberg We need the owner everywhere we access an object, so having it only on `getitem` and `setitem` wouldn't be that useful. And that doesn't help with the cases where there isn't a Python object that can act as the owner.
I think we will need a big refactor of the numpy API to fully support storing objects in arrays.

**Comment by seberg** [comment]
@rlamy the point is that I am _explicitly_ working on those and am doing that "big refactor", so I want to get it right.  Passing in `owner` into ufuncs or casts is actually _easier_, because the new API already has a spot where I can just add it.

**Comment by steve-s** [comment]
> And that doesn't help with the cases where there isn't a Python object that can act as the owner.

So there can be some native memory that holds pointers to Python objects, but does not belong to some other Python object? Sounds like global state?

Re clarity on the owner: in HPy all pointers to Python objects that live in native heap memory, i.e., in your own structs or in memory referenced from those structs, need to be changed to `HPyField`, which allows indirection for those Pythons that need it. `HPyFiled` is mostly useless on its own, you need to `HPyField_Load(ctx, owner, address)` and `HPyField_Store(ctx, owner, address, value)` to get/set a handle to the Python object it references. So something like:
```
  typedef struct {
      PyObject_HEAD
      int magic;
      PyObject *f;
  } MyLegacyType;
```
becomes
```
  typedef struct {
      int magic;
      HPyField f;
  } MyHPyType;
```
In every extension function you need to load the handle from the field, but once loaded, you can use that handle and pass it around. The handle is valid for the duration of the call to `mymethod`, in fact the user should explicitly close it at the end or once not needed:
```
  HPyDef_METH(mymethod, "mymethod", mymethod_impl, HPyFunc_NOARGS)
  static HPy mymethod_impl(HPyContext *ctx, HPy self)
  {
      MyHPyType *data = (MyHPyType*) HPy_Cast(ctx, self);
      HPy field_value = HPyField_Load(ctx, self, data->f);
      my_helper_method(ctx, field_value, ...);
      // ..
      HPy_Close(ctx, field_value);
```
Note that if you want to store to the field, you need the owner, so you need to pass it around in order to call `HPy_Store(ctx, owner, data->f, new_value)`. Note that `owner != data`, in all generosity HPy would like to achieve, the two can be unrelated chunks of memory.

**Comment by steve-s** [comment]
As I see it:
* `HPy` is a short lived fully opaque reference to a Python object. It must be explicitly closed once it's not necessary. Handles must not "outlive" the builtin function call to which they were passed as arguments or during which they were retrieved by some HPy API calls like `HPyLong_FromLong`. I am not sure if this counts as storing the object (not trying to quibble over terminology, but trying to make sure we see it the same way) -- it can be viewed as a reference to an object that lives somewhere else. `HPy` should be stored in local variables, arguments, or memory that has the same lifetime as a local variable.
* `HPyField`: Python object referenced by `HPyField` is alive for at least as long as the owning object (not handle) is alive. Python needs to be aware of this association between the two Python objects in order to be able to do garbage collection or to detect cycles if it uses reference counting. This association is communicated by providing the owner to store/load operations and by visiting the `HPyField` in `tp_traverse`.

To be more concrete in GraalPython, for example:
* `HPy` is just a number that identifies the Python object, but the actual Python object lives somewhere else and there is no way to get from the number stored in `HPy` to the Python object without getting access to internal structures that maintain the mapping. The mapping table itself also lives only for the duration of the current builtin call. For another builtin call we can start with empty mapping again.
* `HPyField` is also a number, but the mapping table for those numbers is specific for each owner object. Once the owner object dies, we know we can throw away that mapping table and remove the association between the two Python objects, which can make them unreachable -> collected by GC.

Since we are discussing these things: it seems to me that even bigger blocker to HPy migration (given HPy design as it is envisaged now) is the global state. HPy does not support static types, only heap types. In general, since you need an owner for anything that lives for longer than one builtin call, global state is not supported, one needs to use module state to store everything "global" (in that case the owner if the module object). In other words, it is basically the same requirements as for subinterpreters support in CPython. Which makes sense, because being "subinterpreter-ready" is one of the goals. I don't want to hijack this discussion, but I wonder if there are any plans in this direction and what you thoughts are.

**Comment by seberg** [comment]
> HPy should be stored in local variables, arguments, or memory that has the same lifetime as a local variable.

Sounds fair, although I am still wondering about "should" or "must"?  But I should probably just retreat from the discussion:  I don't have a clear enough grasp about life-time management, how/what traverse does and _when_ it does that (also, e.g. how does `realloc` work).

My point is that I am *not* worried about creating the traverse function: annoying, but I have a decent idea of _how_.  But I *am* worried that I don't want two functions:
* `copy_item_to_hpyfield(self, item_ptr, new_owner, new_item_ptr)`
* `copy_item_to_hpy(self, item_ptr, handle)`

and I am also worried if we need to do "lifetime management" possibly even for static buffers?!  This might all be solved completely if there is a clear way (even if a bit hacky) to say that we can avoid `HPy` completely by using a special "owner".

> I don't want to hijack this discussion, but I wonder if there are any plans in this direction and what you thoughts are.

I don't have plans for this, and I am not aware of anyone else.  I frankly see sub-interpreters as a problem that needs to be addressed by those most interested in it.  And yes, I was hoping that the HPy effort could end up being the answer here.

NumPy uses globals all over, yes.  Most of that could be module state, some could be type state (is that a thing?).  Some does not have a clear home, because e.g. "converters" don't have access to state.
I guess the use of _type_ objects statically is sprinkled everywhere (even in places where state is very hard to get to) _and_ much of that is public API.

That is a problem, but to be frank, it is a problem I expect to see a solution from HPy/CPython...  NumPy might be particularly chaotic/tricky, but this can't be specific to NumPy?  I feels like there must be a clear path even if that path is tough to make progress on?
* Have API that is not super-fast but also not super-slow and works to get all of these singletons into places _without_ access to any state (there needs to be thread-local/interpreter-state magic to do that).
* Slowly refine NumPy to pass module/type state around where possible.
* Maybe we even have to add a full new public API table that allows users to pass in module state?  That seems _doable_, especially if you do something like `Function(state, ...)` and if `state = NULL`, then `Function` fetches it through a slow mechanism.

**Comment by steve-s** [comment]
Thanks I just wanted to check if there are any plans we may not be aware of and what challenges you already know about. HPy can be the answer. HPy port implies, at least for now, no global state and subinterpreters support so we'll have to bite that bullet.

One thing to note is that with HPy we have to pass HPyContext around already (again: at least for now), so we may consider if we want to support something like "global context state" perhaps alongside module state. Accessing such state would still need a HPyContext instance. That's for a separate discussion, though.

> Maybe we even have to add a full new public API table that allows users to pass in module state

Yes this will be necessary already just to pass the `HPyContext` to the API. I was thinking about introducing "H" prefixed variants to the regular API table, but having another table for HPy NumPy API sounds even cleaner. Maybe the names should still have "H" prefix though.

**Comment by rlamy** [comment]
> I will probably just propose to include an opaque owner for new API, I think.
Note that the API will have to change to convert owner from `PyObject *` to `HPy` and also to add the HPyContext. It might be more future-proof to have an opaque context, like for the cast functions (thought if it's opaque, I guess it's just semantics).

**Comment by seberg** [comment]
The cast functions already have a struct passed in now, we can add whatever we want trivially.  And yes, I expect e.g. for CPython we should start passing in the Interpreter state (which is probably much the same as `ctx` here) – although the one time I asked on CPython whether I should do that the "yes please" seemed a bit half-hearted...
`get/set` are a bit special in that it might be nice to just pass `ctx` and `owner` directly, since they are always required and there is no larger concept around them.

I don't mind packing them up into a `void *context` for now though, if it seems easier.

**Comment by mattip** [comment]
> I don't mind packing them up into a void *context for now though, if it seems easier.

This seems like a reasonable plan

**Comment by rlamy** [comment]
Closing. General discussions of the numpy port can continue at #137.
