### ISSUE TITLE
API to acquire/release the GIL

### ISSUE THREAD

**Issue by thedrow** [hpyproject/hpy#34]
Right now hpy doesn't have an API to acquire or release the GIL.
It'd be useful for C extensions to have one which acquires/releases the GIL when a GIL is used in a Python implementation and to make it a no-op when it is not.

**Comment by arigo** [comment]
ISTM that the various ways to do it in CPython can all be replaced by the following simple alternative:

``HPyGIL_Lock(ctx)``: waits for and acquire the GIL in the given context.  Returns 0 if the GIL was already acquired by the running thread (guaranteed single-thread-deadlock protection).

``HPyGIL_Unlock(ctx)``: release the GIL.

This should be flexible enough to support multiple subinterpreters, for example (with multiple 'ctx').  The GIL itself can be either a single global lock, or one per subinterpreter (or nothing at all, in which case ``HPyGIL_Lock(ctx)`` can always return 0).

This would allow us to replace the common CPython idioms with a version which clearly says what it is doing:

    Py_BEGIN_ALLOW_THREADS
    ... Do some blocking I/O operation ...
    Py_END_ALLOW_THREADS

becomes

    HPyGIL_Unlock(ctx);
    ...
    HPyGIL_Lock(ctx);

and

    PyGILState_STATE gstate = PyGILState_Ensure();
    ...
    PyGILState_Release(gstate);

becomes

    int acquired = HPyGIL_Lock(ctx);
    ...
    if (acquired) HPyGIL_Unlock(ctx);

This sounds possible to implement on top of CPython with a bit of [abstraction inversion](https://en.wikipedia.org/wiki/Abstraction_inversion).

**Comment by thedrow** [comment]
How does such an implementation look on PyPy?
How does `HPyGIL_Lock` and `HPyGIL_Unlock` look like behind the scenes?

**Comment by arigo** [comment]
The API is in ``rpython.rlib.rgil``, functions ``acquire()`` and ``release()`` and ``am_I_holding_the_GIL()``.

**Comment by thedrow** [comment]
I didn't know these are public. Thanks.

**Comment by antocuni** [comment]
> I didn't know these are public. Thanks.

maybe it's already obvious, but I think it's better to explain for the sake of the casual reader: `rpython.rlib.rgil.*` functions are "public" and available only if you are writing in RPython. They can't be used/accessed/called directly from pure python, of course.

**Comment by thedrow** [comment]
What's unclear to me, is how we expose those functions to C? Is it the other way around? Do we provide rffi bindings to HPy?

I might not getting the design right but as far as I saw there is no document explaining how HPy works with PyPy which is why I asked the original question regarding PyPy.

**Comment by antocuni** [comment]
> What's unclear to me, is how we expose those functions to C? Is it the other way around? Do we provide rffi bindings to HPy?
I might not getting the design right but as far as I saw there is no document explaining how HPy works with PyPy which is why I asked the original question regarding PyPy.
Maybe we should write documentation about it as well.

So, in your extension you write:
```c
HPyLong_FromLong(ctx, 42);
```

This is a `static inline` functions which is defined inside `autogen_trampolines.h`:
https://github.com/hpyproject/hpy/blob/11af3c91129226431d75b475cba858007e71969c/hpy/devel/include/universal/autogen_trampolines.h#L23-L25

So, the actual implementation depends on what are the function pointers inside the context.  In the PyPy repo, we have the `_hpy_universal` module which provides an `HPyContext` whose function pointers are written in RPython: that's how you call from HPy to PyPy, there is no need to provide rffi bindings or similar.
