### ISSUE TITLE
Make universal-ABI modules installable

### ISSUE THREAD

**Issue by rlamy** [hpyproject/hpy#85]
ATM, there is no way to properly install a module that uses the universal ABI. 
At first glance, `python setup.py --hpy-abi=universal install` looks like it might work. But while it does create a valid `pof.hpy.so` and sticks it in `site-packages/`, the `pof.py` shim that setuptools creates isn't HPy-aware.
In any case, that solution uses the deprecated `.egg` format, and we should rather find something that works with pip.

**Comment by rlamy** [comment]
BTW, replacing setuptools' shim with something like below does work correctly, but I don't know how to tell setuptools to produce it.

```python
class Spec:
    def __init__(self, name, origin):
        self.name = name
        self.origin = origin

def __bootstrap__():
    global __loader__, __file__
    import sys, pkg_resources
    from hpy.universal import load_from_spec
    __file__ = pkg_resources.resource_filename(__name__, 'piconumpy_hpy.hpy.so')
    m = load_from_spec(Spec('piconumpy_hpy', __file__))
    sys.modules[__name__] = m
__bootstrap__()
```

**Comment by antocuni** [comment]
I did a tiny improvement about this in PR #105 : instead of installing something which doesn't work, it complains clearly.

About a more proper solution: automatically generating a shim similar to what `bdist_egg` does might work, but we need to ensure that it works also with `bdist_wheel` (which I think it's what it's used by pip under the hood).

Moreover, we need to think about how this will interact with the debug mode: to load a module in debug mode, we always need the universal binary. So we might want to support an installation/packaging mode in which we build/distribute BOTH versions (CPython and universal) on CPython, but only universal on pypy, and possibly other combinations on other implementations.

So, whatever we decide to do it needs to be well designed, and I think it's better to wait until we have a debug mode to have our ideas cleaner.

**Comment by hodgestar** [comment]
The universal ABI modules have been installable for awhile now (since #124 was merged :).
